version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: haravan-store
      MYSQL_USER: tuantai
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
